--npm install react-native-calendars
--npm install react-native-chart-kit @types/react-native-chart-kit
--npx expo install @react-native-community/datetimepicker
--npm install expo-image-picker expo-file-system
--npm install expo-image-picker
--npm install multer
--npm install react-native-chart-kit react-native-svg @gorhom/bottom-sheet
--npm install pg @types/pg
--npm install express pg cors
--npm install express cors
--npm install --save-dev @types/express @types/cors typescript ts-node